version: "3"

services:
  my-awesome-database:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress_password
    container_name: my-awesome-database
    volumes:
      - mysql:/var/lib/mysql
    networks:
      - my-awesome-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      retries: 2
      timeout: 5s
      interval: 5s

  my-awesome-wordpress:
    build: .
    container_name: my-awesome-wordpress
    restart: unless-stopped
    ports:
      - 8080:80
    networks:
      - my-awesome-network
    depends_on:
      - my-awesome-database
    volumes:
      - wordpress:/var/www/html
    environment:
      WORDPRESS_DB_HOST: my-awesome-database:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress_password
      WORDPRESS_DB_NAME: wordpress

networks:
  my-awesome-network:
    driver: bridge

volumes:
  mysql:
  wordpress:
